s1=set([1,2,3])#set看作是数学上无序和无重复元素的组合两个set可做数学意义上的交集并集等。
s2=set([4,5,6])
s1.add(4)#要干什么一般都是什么什么函数.什么
s1.remove(2)
print(s1)#因为s在这里是一种函数，所以不用再加双引号，否则输出不对
print(s1&s2)#&是交集
print(s1|s2)#|是交集
#set就是没有存储对应的value，这是什莫意思？
a=['c','b','a']
a.sort()
print(a)
a='abc'
a.replace('a','A')
print(a)#为什么是输出abc呢，a是变量，而‘abc’才是字符串对象，有些时候，a的对象是‘abc’，其实是a是一个变量，它指向的对象才是abc，
#replace方法是创建了一个新的字符串b，b则是Abc。
#所以，str是不变对象，list是可变对象
#改一下
a='abc'
b=a.replace('a','A')
print(b)#上面那个输出a还是输出本身的a，这个呢给他创建了一个新的b，所以就会改变了。
